services:
  app:
    build: .
    ports:
      - "9137:8080"
    environment:
      - SPRING_MAIL_HOST
      - SPRING_MAIL_PASSWORD
      - SPRING_MAIL_PORT
      - SPRING_MAIL_USERNAME
      - SPRING_DATASOURCE_PASSWORD
      - SPRING_DATASOURCE_USERNAME
      - SPRING_DATASOURCE_URL
    depends_on:
      - db
  db:
    image: mariadb:11.3
    container_name: mariadb
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD
      - MARIADB_DATABASE
      - MARIADB_USER
      - MARIADB_PASSWORD
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: